### PR TITLE
Default jvm settings to use "-client". If "-server" is specified, use "-...

### PR DESCRIPTION
**Pull request by dinedal**
...server" instead.

Only write each jvm-opt once

``` clojure
(jvm-options {:jvm-opts ["-server"] :name "test" :version "0.0.1"})
;"-server -Dtest.version=0.0.1"
(jvm-options {:jvm-opts ["-client"] :name "test" :version "0.0.1"})
;"-client -Dtest.version=0.0.1"
(jvm-options {:jvm-opts ["-Xmx=3000m"] :name "test" :version "0.0.1"})
;"-Xmx=3000m -client -Dtest.version=0.0.1"
(jvm-options {:jvm-opts ["-Xmx=3000m" "-server"] :name "test" :version "0.0.1"})
;"-Xmx=3000m -server -Dtest.version=0.0.1"
```

### CODE REVIEW

**Comment by dinedal** [comment]
cc @drewr

**Comment by Raynes** [comment]
Looks good to me. I'm currently waiting for a bus, so I'll take a closer look and merge in a bit.

**Comment by drewr** [comment]
+1

**Comment by Raynes** [comment]
Deployed 0.3.4. Thanks for the contributions guys.

**Comment by DAddYE** [comment]
Thanks @dinedal and @Raynes

**Pull request merged**
